language: node_js
node_js: '12'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install --frozen-lockfile --ignore-engines
jobs:
  fast_finish: true
  include:
    - name: PR Checks
      if: type = pull_request
      script: yarn beemo run-script pull-request-checks
      node_js: '12'
    - name: Test @ 8
      script: yarn test
      node_js: '8'
    - name: Test @ 10
      script: yarn test
      node_js: '8'
    - name: Test @ 12
      script: yarn test
      node_js: '12'
notifications:
  email: false
cache:
  yarn: true
